In [2]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import OneHotEncoder
#Load dataset
cancer = datasets.load_breast_cancer()

In [3]:
# print the names of the features
print("Features: ", cancer.feature_names)

# print the label type of cancer
print("Labels: ", cancer.target_names)

# print data(feature)shape
cancer.data.shape

print("\nData: ",cancer.data)
print("\nTarget: ",cancer.target)

Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Labels:  ['malignant' 'benign']

Data:  [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-0

In [9]:
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(cancer.data,
                        cancer.target, test_size = 0.4, random_state = 48)

In [9]:
print(dataset,Y_rows)

    O  R  S  C  H  M  High  Low  Normal  F  T
0   0  1  0  0  1  0     0    0       1  1  0
1   0  1  0  0  1  0     1    0       0  0  1
2   1  0  0  0  1  0     0    0       1  1  0
3   0  0  1  0  0  1     0    0       1  1  0
4   0  0  1  1  0  0     0    0       1  1  0
5   0  0  1  1  0  0     0    1       0  0  1
6   1  0  0  1  0  0     0    0       1  0  1
7   0  1  0  0  0  1     0    0       1  1  0
8   0  1  0  1  0  0     0    1       0  1  0
9   0  0  1  0  0  1     1    0       0  1  0
10  0  1  0  0  0  1     1    0       0  0  1
11  1  0  0  0  0  1     0    1       0  0  1
12  1  0  0  0  1  0     0    0       1  1  0
13  0  0  1  0  0  1     0    0       1  0  1 [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [5]:
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [6]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.956140350877193


In [7]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[ 68,   6],
       [  4, 150]], dtype=int64)

In [8]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.94444444 0.96153846]
recall: [0.91891892 0.97402597]
